future: true
permalink: /:title/
url: http://luckpiky.github.io
name: Luckpiky
author: luckpiky
qq: 
email: hustcat@gmail.com
duoshuo: hustcat
beian: 
cnzz: 
weibo: 
github: 
paginate: 20
highlighter: rouge
truncate: true
about: ""
