markdown: rdiscount
future: true
permalink: /:title/
url: http://luckpiky.github.io
name: Luckpiky
author: luckpiky
qq: 
email: luckpiky@163.com
paginate: 20
highlighter: rouge
truncate: true
about: "胖工程狮一头，喜欢吃肉，也爱睡觉。"
